name: Deploy App

on:
  push:
    branches: [master]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd ~/projects/node-express-digital-ocean-example
            # rm -Rf node-express-digital-ocean-example
            # git clone git@github.com:alextomas80/node-express-digital-ocean-example.git node-express-digital-ocean-example
            # npm install
            git pull origin master
            echo "Deployment successful to Digital Ocean"

